# Generated by Django 5.2.5 on 2025-08-27 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Tunai'), ('BANK_BCA', 'Transfer Bank - BCA'), ('BANK_BRI', 'Transfer Bank - BRI'), ('BANK_BSI', 'Transfer Bank - BSI'), ('EWALLET_GOPAY', 'E-wallet - GoPay'), ('EWALLET_DANA', 'E-wallet - DANA')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('CONFIRMED', 'Dikonfirmasi'), ('PREPARING', 'Sedang Diproses'), ('READY', 'Siap Diambil'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warung.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warung.order')),
            ],
        ),
    ]
